server:
  port: 9090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "prod"

build:
  version: "2.1.4"

contacts:
  message: "Welcome to Bank cards Microservice"
  contactDetails:
    name: "Dragi Pantović - Developer"
    email: "dtm.pantovic@gmail.com"
  onCallSupport:
    - (+91) 9872109455
    - (+91) 9884567822