services:
  accounts:
    image: "dragipan/accounts:1.0.0"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservice

  loans:
    image: "dragipan/loans:1.0.0"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservice

  cards:
    image: "dragipan/cards:1.0.0"
    container_name: cards-ms
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - microservice

networks:
  microservice:
    driver: "bridge"
