services:
  network-deploy-service:
    networks:
      - microservice

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: mysql
    healthcheck:
      test: "mysqladmin ping -h localhost --silent"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"


  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka
