server:
  http_listen_port: 3100

distrubutor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

compactor:
  compaction:
    compatcion_window: 1h
    max_comapction_objects: 1_000_000
    block_retention: 1h
    comacted_block_retention: 10m
