spring:
  application:
    name: "spring-cloud"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/dragiPan/Spring-Config-Files.git"
          default-label: main
          timeout: 10000
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

  logging:
    pattern:
      level: "%5p[${spring.application.name},%X{trace_id},%X{span_id}]"


server:
  port: 8071
encrypt:
  key: "9JD01L48SMN99AK139R01LS91A"