apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: accountsdb
spec:
  serviceName: "accountsdb"
  replicas: 1
  selector:
    matchLabels:
      app: accountsdb
  template:
    metadata:
      labels:
        app: accountsdb
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "accountsdb"
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          volumeMounts:
            - name: mysql-data
              mountPath: /mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: accountsdb-pvc
        - name: init-sql

---
apiVersion: v1
kind: Service
metadata:
  name: accountsdb
spec:
  selector:
    app: accountsdb
  type: ClusterIP
  ports:
    - name: mysql-port
      protocol: TCP
      port: 3306
      targetPort: 3306
    - name: external-port
      protocol: TCP
      port: 3333
      targetPort: 3306
