apiVersion: apps/v1
kind: Deployment
metadata:
    name: accounts-deployment
    labels:
        app: accounts
spec:
    replicas: 1
    selector:
        matchLabels:
            app: accounts
    template:
        metadata:
            labels:
                app: accounts
        spec:
            initContainers:
              - name: wait-for-accountsdb
                image: busybox
                command: [ 'sh', '-c', 'until nc -z accountsdb 3306; do sleep 5; done' ]

              - name: wait-for-configserver
                image: busybox
                command: [ 'sh', '-c', 'until nc -z configserver 8071; do sleep 5; done' ]

              - name: wait-for-eurekaserver
                image: busybox
                command: [ 'sh', '-c', 'until nc -z eurekaserver 8070; do sleep 5; done' ]

            containers:
                - name: accounts
                  image: dragipan/accounts:1.0.0
                  ports:
                    - containerPort: 8080
                  env:
                    - name: OTEL_EXPORTER_OTLP_ENDPOINT
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: OTEL_EXPORTER_OTLP_ENDPOINT

                    - name: OTEL_SERVICE_NAME
                      value: "accounts-service"

                    - name: OTEL_RESOURCE_ATTRIBUTES
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: OTEL_RESOURCE_ATTRIBUTES

                    - name: OTEL_METRICS_EXPORTER
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: OTEL_METRICS_EXPORTER

                    - name: OTEL_LOGS_EXPORTER
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: OTEL_LOGS_EXPORTER

                    - name: SPRING_CONFIG_IMPORT
                      valueFrom:
                        configMapKeyRef:
                            name: microservice-configmap
                            key: SPRING_CONFIG_IMPORT
                    -  name: SPRING_APPLICATION_NAME
                       valueFrom:
                         configMapKeyRef:
                            name: microservice-configmap
                            key: ACCOUNTS_APPLICATION_NAME
                    - name: SPRING_DATASOURCE_URL
                      value: jdbc:mysql://accountsdb:3306/accountsdb
                    - name: SPRING_DATASOURCE_USERNAME
                      valueFrom:
                        configMapKeyRef:
                            name: microservice-configmap
                            key: SPRING_DATASOURCE_USERNAME
                    - name: SPRING_DATASOURCE_PASSWORD
                      valueFrom:
                        configMapKeyRef:
                            name: microservice-configmap
                            key: SPRING_DATASOURCE_PASSWORD

                  readinessProbe:
                    httpGet:
                      path: /actuator/health/readiness
                      port: 8080
                    initialDelaySeconds: 10
                    periodSeconds: 5
                    timeoutSeconds: 3
                    failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: accounts
spec:
  selector:
    app: accounts
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080



