apiVersion: apps/v1
kind: Deployment
metadata:
  name: alloy-deployment
  labels:
    app: alloy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      containers:
        - name: alloy
          image: grafana/alloy:v1.5.1
          command:
            - "/usr/bin/alloy"
          args:
            - "run"
            - "--server.http.listen-addr=0.0.0.0:12345"
            - "--storage.path=/var/lib/alloy/data"
            - "/etc/alloy/config.alloy"
          ports:
            - containerPort: 12345
          volumeMounts:
            - name: alloy-config
              mountPath: /etc/alloy
              readOnly: true
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: alloy-data
              mountPath: /alloy
      volumes:
        - name: alloy-config
          configMap:
            name: alloy-config
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: alloy-data
          persistentVolumeClaim:
            claimName: alloy-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: alloy
spec:
  selector:
    app: alloy
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345
