apiVersion: apps/v1
kind: Deployment
metadata:
    name: cards-deployment
    labels:
        app: cards
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cards
    template:
        metadata:
            labels:
                app: cards
        spec:
            initContainers:
              - name: wait-for-cardsdb
                image: busybox
                command: [ 'sh', '-c', 'until nc -z cardsdb 3306; do sleep 5; done' ]

              - name: wait-for-configserver
                image: busybox
                command: [ 'sh', '-c', 'until nc -z configserver 8071; do sleep 5; done' ]

              - name: wait-for-eurekaserver
                image: busybox
                command: [ 'sh', '-c', 'until nc -z eurekaserver 8070; do sleep 5; done' ]
            containers:
                - name: cards
                  image: dragipan/cards:1.0.0
                  ports:
                    - containerPort: 9090
                  env:
                    - name: SPRING_CONFIG_IMPORT
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: SPRING_CONFIG_IMPORT
                    - name: SPRING_APPLICATION_NAME
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: CARDS_APPLICATION_NAME
                    - name: SPRING_DATASOURCE_URL
                      value: jdbc:mysql://cardsdb:3306/cardsdb
                    - name: SPRING_DATASOURCE_USERNAME
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: SPRING_DATASOURCE_USERNAME
                    - name: SPRING_DATASOURCE_PASSWORD
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: SPRING_DATASOURCE_PASSWORD
                    - name: OTEL_EXPORTER_OTLP_ENDPOINT
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: OTEL_EXPORTER_OTLP_ENDPOINT

                    - name: OTEL_SERVICE_NAME
                      value: "cards-service"

                    - name: OTEL_RESOURCE_ATTRIBUTES
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: OTEL_RESOURCE_ATTRIBUTES

                    - name: OTEL_METRICS_EXPORTER
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: OTEL_METRICS_EXPORTER

                    - name: OTEL_LOGS_EXPORTER
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: OTEL_LOGS_EXPORTER
                  readinessProbe:
                    httpGet:
                      path: /actuator/health/readiness
                      port: 9090
                    initialDelaySeconds: 10
                    periodSeconds: 5
                    timeoutSeconds: 3
                    failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: cards
spec:
  selector:
    app: cards
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
