apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo waiting for RabbitMQ; sleep 5; done']

      containers:
        - name: configserver
          image: dragipan/spring-cloud:1.0.0
          ports:
            - containerPort: 8071
          env:
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: microservice-configmap
                  key: SPRING_RABBITMQ_HOST

            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: microservice-configmap
                  key: SPRING_RABBITMQ_PORT

            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: microservice-configmap
                  key: SPRING_RABBITMQ_USERNAME

            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: microservice-configmap
                  key: SPRING_RABBITMQ_PASSWORD

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8071
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  selector:
    app: configserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
