apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deployment
  labels:
    app: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      initContainers:
        - name: wait-for-configserver
          image: busybox
          command: [ 'sh', '-c', 'until nc -z configserver 8071; do sleep 5; done' ]
      containers:
        - name: eurekaserver
          image: dragipan/eurekaserver:1.0.0
          ports:
            - containerPort: 8070
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: microservice-configmap
                  key: EUREKA_APPLICATION_NAME
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: microservice-configmap
                  key: SPRING_CONFIG_IMPORT
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8070
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
spec:
  selector:
    app: eurekaserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
