apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      initContainers:
        - name: wait-for-loki-read
          image: busybox
          command: ['sh', '-c', 'until nc -z loki-read 3100; do sleep 5; done']
        - name: wait-for-loki-write
          image: busybox
          command: ['sh', '-c', 'until nc -z loki-write 3100; do sleep 5; done']
      containers:
        - name: gateway
          image: nginx:1.25.3
          ports:
            - name: http
              containerPort: 3100
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          command: ["sh", "-c", "/docker-entrypoint.sh nginx -g 'daemon off;'"]
          readinessProbe:
            httpGet:
              path: /
              port: 3100
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: microservice-configmap
                  key: OTEL_EXPORTER_OTLP_ENDPOINT

            - name: OTEL_SERVICE_NAME
              value: "gateway-service"

            - name: OTEL_RESOURCE_ATTRIBUTES
              valueFrom:
                configMapKeyRef:
                  name: microservice-configmap
                  key: OTEL_RESOURCE_ATTRIBUTES

            - name: OTEL_METRICS_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: microservice-configmap
                  key: OTEL_METRICS_EXPORTER

            - name: OTEL_LOGS_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: microservice-configmap
                  key: OTEL_LOGS_EXPORTER

      volumes:
        - name: nginx-config
          configMap:
            name: gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3111
      targetPort: 3100
