apiVersion: apps/v1
kind: Deployment
metadata:
    name: gatewayserver-deployment
    labels:
        app: gatewayserver
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gatewayserver
    template:
        metadata:
            labels:
                app: gatewayserver
        spec:
            initContainers:
              - name: wait-for-accounts
                image: busybox
                command: [ 'sh', '-c', 'until nc -z accounts 8080; do sleep 5; done' ]

              - name: wait-for-loans
                image: busybox
                command: [ 'sh', '-c', 'until nc -z loans 8090; do sleep 5; done' ]

              - name: wait-for-cards
                image: busybox
                command: [ 'sh', '-c', 'until nc -z cards 9090; do sleep 5; done' ]

              - name: wait-for-redis
                image: busybox
                command: [ 'sh', '-c', 'until nc -z redis 6379; do sleep 5; done' ]

            containers:
                - name: gatewayserver
                  image: dragipan/gatewayserver:1.0.0
                  ports:
                    - containerPort: 8072
                  env:
                    - name: SPRING_CONFIG_IMPORT
                      valueFrom:
                        configMapKeyRef:
                            name: microservice-configmap
                            key: SPRING_CONFIG_IMPORT
                    - name: SPRING_APPLICATION_NAME
                      valueFrom:
                        configMapKeyRef:
                            name: microservice-configmap
                            key: GATEWAYSERVER_APPLICATION_NAME
---
apiVersion: v1
kind: Service
metadata:
    name: gatewayserver
spec:
    selector:
        app: gatewayserver
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 8072
          targetPort: 8072