apiVersion: apps/v1
kind: Deployment
metadata:
    name: gatewayserver-deployment
    labels:
        app: gatewayserver
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gatewayserver
    template:
        metadata:
            labels:
                app: gatewayserver
        spec:
            initContainers:
              - name: wait-for-accounts
                image: busybox
                command: [ 'sh', '-c', 'until nc -z accounts 8080; do sleep 5; done' ]

              - name: wait-for-loans
                image: busybox
                command: [ 'sh', '-c', 'until nc -z loans 8090; do sleep 5; done' ]

              - name: wait-for-cards
                image: busybox
                command: [ 'sh', '-c', 'until nc -z cards 9090; do sleep 5; done' ]

              - name: wait-for-redis
                image: busybox
                command: [ 'sh', '-c', 'until nc -z redis 6379; do sleep 5; done' ]

            containers:
                - name: gatewayserver
                  image: dragipan/gatewayserver:1.0.0
                  ports:
                    - containerPort: 8072
                  env:
                    - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE

                    - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: EUREKA_CLIENT_REGISTER_WITH_EUREKA

                    - name: EUREKA_CLIENT_FETCH_REGISTRY
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: EUREKA_CLIENT_FETCH_REGISTRY

                    - name: SPRING_CONFIG_IMPORT
                      valueFrom:
                        configMapKeyRef:
                            name: microservice-configmap
                            key: SPRING_CONFIG_IMPORT
                    - name: SPRING_APPLICATION_NAME
                      valueFrom:
                        configMapKeyRef:
                            name: microservice-configmap
                            key: GATEWAYSERVER_APPLICATION_NAME
                    - name: OTEL_EXPORTER_OTLP_ENDPOINT
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: OTEL_EXPORTER_OTLP_ENDPOINT

                    - name: OTEL_SERVICE_NAME
                      value: "gatewayserver-service"

                    - name: OTEL_RESOURCE_ATTRIBUTES
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: OTEL_RESOURCE_ATTRIBUTES

                    - name: OTEL_METRICS_EXPORTER
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: OTEL_METRICS_EXPORTER

                    - name: OTEL_LOGS_EXPORTER
                      valueFrom:
                        configMapKeyRef:
                          name: microservice-configmap
                          key: OTEL_LOGS_EXPORTER

                  readinessProbe:
                    httpGet:
                      path: /actuator/health/readiness
                      port: 8072
                    initialDelaySeconds: 10
                    periodSeconds: 5
                    timeoutSeconds: 3
                    failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
    name: gatewayserver
spec:
    selector:
        app: gatewayserver
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 8072
          targetPort: 8072