apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loansdb
spec:
  serviceName: "loansdb"
  replicas: 1
  selector:
    matchLabels:
      app: loansdb
  template:
    metadata:
      labels:
        app: loansdb
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "loansdb"
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          volumeMounts:
            - name: mysql-data
              mountPath: /mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: loansdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: loansdb
spec:
  selector:
    app: loansdb
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
