apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.1.0
          args:
            - "-config.file=/etc/loki/loki-config.yml"
          volumeMounts:
            - name: loki-storage
              mountPath: /loki
      volumes:
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  selector:
    app: loki
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
