apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      initContainers:
        - name: wait-for-minio
          image: busybox
          command: [ 'sh', '-c', 'until nc -z minio 9000; do sleep 5; done' ]
      containers:
        - name: minio
          image: minio/minio:RELEASE.2024-12-13T22-19-12Z
          args:
            - server
            - /data
          env:
            - name: MINIO_ROOT_USER
              value: "loki"
            - name: MINIO_ROOT_PASSWORD
              value: "supersecret"
            - name: MINIO_PROMETHEUS_AUTH_TYPE
              value: "public"
            - name: MINIO_UPDATE
              value: "off"
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: minio-storage
              mountPath: /data
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
