apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.0.0
          args: ["-config.file=/etc/tempo/config.yml"]
          ports:
            - containerPort: 3100
            - containerPort: 4317
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo/config.yml
              subPath: tempo.yml
          readinessProbe:
            httpGet:
              path: /ready
              port: 3100
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
            items:
              - key: tempo.yml
                path: config.yml
        - name: tempo-data
          persistentVolumeClaim:
            claimName: tempo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  type: ClusterIP
  ports:
    - name: "http-metrics"
      protocol: TCP
      port: 3100
      targetPort: 3100

    - name: "grpc-metrics"
      protocol: TCP
      port: 4317
      targetPort: 4317