apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  labels:
    app: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.0.0
          args: ["-config.file=/etc/tempo/config.yml"]
          ports:
            - containerPort: 3100
            - containerPort: 4317
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
    - protocol: TCP
      port: 4317
      targetPort: 4317